import doctor from "@/assets/dentists/doctor-1.jpeg";

export const DOCTORS_SECTION = {
  doctors: [
    {
      name: "Harvey Yerik",
      special: "Ingeniero de software",
      image: doctor,
      text: "Lorem ipsum dolor sit ametaew, ddaasf so the conaconsectetur adipiscing elit. Etiam tellus aefc ipsum, pellentesque quisdq dapibus et, faucibus a nibh. Lorem ipsum dolor sit, but is increible",
      email: "",
      fb: "",
      phone: "",
      url: "",
    },
    {
      name: "Harvey Yerik",
      special: "Ingeniero de software",
      image: doctor,
      text: "Lorem ipsum dolor sit ametaew, ddaasf so the conaconsectetur adipiscing elit. Etiam tellus aefc ipsum, pellentesque quisdq dapibus et, faucibus a nibh. Lorem ipsum dolor sit, but is increible",
      email: "",
      fb: "",
      phone: "",
      url: "",
    },
    {
      name: "Harvey Yerik",
      special: "Ingeniero de software",
      image: doctor,
      text: "Lorem ipsum dolor sit ametaew, ddaasf so the conaconsectetur adipiscing elit. Etiam tellus aefc ipsum, pellentesque quisdq dapibus et, faucibus a nibh. Lorem ipsum dolor sit, but is increible",
      email: "",
      fb: "",
      phone: "",
      url: "",
    },
    {
      name: "Harvey Yerik",
      special: "Ingeniero de software",
      image: doctor,
      text: "Lorem ipsum dolor sit ametaew, ddaasf so the conaconsectetur adipiscing elit. Etiam tellus aefc ipsum, pellentesque quisdq dapibus et, faucibus a nibh. Lorem ipsum dolor sit, but is increible",
      email: "",
      fb: "",
      phone: "",
      url: "",
    },
    {
      name: "Harvey Yerik",
      special: "Ingeniero de software",
      image: doctor,
      text: "Lorem ipsum dolor sit ametaew, ddaasf so the conaconsectetur adipiscing elit. Etiam tellus aefc ipsum, pellentesque quisdq dapibus et, faucibus a nibh. Lorem ipsum dolor sit, but is increible",
      email: "",
      fb: "",
      phone: "",
      url: "",
    },
  ],
  title: "Conoce a nuestros dentistas",
};
